### ISSUE TITLE
Job error with Resque

### ISSUE THREAD

**Issue by rinaldifonseca** [jstorimer/delayed_paperclip#15]
Hi,

When I try to upload a image I get the error:

obs: I'm using Ruby EE, Rails 2.3.8, Redis 2.0.5 and Resque 1.0.10

```
 uninitialized constant ResquePaperclipJob

/home/rinaldi/.rvm/gems/ree-1.8.7-2010.02@rails238/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:443:in `load_missing_constant'
/home/rinaldi/.rvm/gems/ree-1.8.7-2010.02@rails238/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:80:in `const_missing'
/home/rinaldi/.rvm/gems/ree-1.8.7-2010.02@rails238/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:92:in `const_missing'
/home/rinaldi/.rvm/gems/ree-1.8.7-2010.02@rails238/gems/resque-1.10.0/lib/resque/helpers.rb:58:in `const_get'
/home/rinaldi/.rvm/gems/ree-1.8.7-2010.02@rails238/gems/resque-1.10.0/lib/resque/helpers.rb:58:in `constantize'
/home/rinaldi/.rvm/gems/ree-1.8.7-2010.02@rails238/gems/resque-1.10.0/lib/resque/helpers.rb:57:in `each'
/home/rinaldi/.rvm/gems/ree-1.8.7-2010.02@rails238/gems/resque-1.10.0/lib/resque/helpers.rb:57:in `constantize'
/home/rinaldi/.rvm/gems/ree-1.8.7-2010.02@rails238/gems/resque-1.10.0/lib/resque/job.rb:174:in `payload_class'
/home/rinaldi/.rvm/gems/ree-1.8.7-2010.02@rails238/gems/resque-1.10.0/lib/resque/job.rb:111:in `perform'
/home/rinaldi/.rvm/gems/ree-1.8.7-2010.02@rails238/gems/resque-1.10.0/lib/resque/worker.rb:157:in `perform'
/home/rinaldi/.rvm/gems/ree-1.8.7-2010.02@rails238/gems/resque-1.10.0/lib/resque/worker.rb:124:in `work'
/home/rinaldi/.rvm/gems/ree-1.8.7-2010.02@rails238/gems/resque-1.10.0/lib/resque/worker.rb:110:in `loop'
/home/rinaldi/.rvm/gems/ree-1.8.7-2010.02@rails238/gems/resque-1.10.0/lib/resque/worker.rb:110:in `work'
/home/rinaldi/.rvm/gems/ree-1.8.7-2010.02@rails238/gems/resque-1.10.0/lib/resque/tasks.rb:24
/home/rinaldi/.rvm/gems/ree-1.8.7-2010.02@rails238/gems/rake-0.8.7/lib/rake.rb:636:in `call'
/home/rinaldi/.rvm/gems/ree-1.8.7-2010.02@rails238/gems/rake-0.8.7/lib/rake.rb:636:in `execute'
/home/rinaldi/.rvm/gems/ree-1.8.7-2010.02@rails238/gems/rake-0.8.7/lib/rake.rb:631:in `each'
/home/rinaldi/.rvm/gems/ree-1.8.7-2010.02@rails238/gems/rake-0.8.7/lib/rake.rb:631:in `execute'
/home/rinaldi/.rvm/gems/ree-1.8.7-2010.02@rails238/gems/rake-0.8.7/lib/rake.rb:597:in `invoke_with_call_chain'
/home/rinaldi/.rvm/rubies/ree-1.8.7-2010.02/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/home/rinaldi/.rvm/gems/ree-1.8.7-2010.02@rails238/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
/home/rinaldi/.rvm/gems/ree-1.8.7-2010.02@rails238/gems/rake-0.8.7/lib/rake.rb:583:in `invoke'
/home/rinaldi/.rvm/gems/ree-1.8.7-2010.02@rails238/gems/rake-0.8.7/lib/rake.rb:2051:in `invoke_task'
/home/rinaldi/.rvm/gems/ree-1.8.7-2010.02@rails238/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
/home/rinaldi/.rvm/gems/ree-1.8.7-2010.02@rails238/gems/rake-0.8.7/lib/rake.rb:2029:in `each'
/home/rinaldi/.rvm/gems/ree-1.8.7-2010.02@rails238/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
/home/rinaldi/.rvm/gems/ree-1.8.7-2010.02@rails238/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/home/rinaldi/.rvm/gems/ree-1.8.7-2010.02@rails238/gems/rake-0.8.7/lib/rake.rb:2023:in `top_level'
/home/rinaldi/.rvm/gems/ree-1.8.7-2010.02@rails238/gems/rake-0.8.7/lib/rake.rb:2001:in `run'
/home/rinaldi/.rvm/gems/ree-1.8.7-2010.02@rails238/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/home/rinaldi/.rvm/gems/ree-1.8.7-2010.02@rails238/gems/rake-0.8.7/lib/rake.rb:1998:in `run'
/home/rinaldi/.rvm/gems/ree-1.8.7-2010.02@rails238/gems/rake-0.8.7/bin/rake:31
/home/rinaldi/.rvm/gems/ree-1.8.7-2010.02@rails238/bin/rake:19:in `load'
/home/rinaldi/.rvm/gems/ree-1.8.7-2010.02@rails238/bin/rake:19
```

**Comment by jstorimer** [comment]
Rinaldi,

I tried out the gem with you environment setup and everything worked fine.

It looks like you're running a rake task here.  Can you give some more background? What rake task are you running here?

If you're using bundler, what does your Gemfile look like?

If you're using config.gem, what does the output of `rake gems` look like?

What does your model look like?

**Comment by rinaldifonseca** [comment]
Hi,

I forget tell you that in my development environment everythings works, but in production not.

The only diference is that in production I'm using ubuntu server 10.04, and my local machine I'm using ubuntu 9.04.

I'm runing  redis-server and starting a worker with the rake task: QUEUE=\* rake environment resque:work

After that, I can access resque-web for see my jobs. But when I upload some image I get the error above.

I'm not using bundler, and in my config.gem  I just set: 

config.gem 'resque'
config.gem 'delayed_paperclip'

My model look like this:

class User < ActiveRecord::Base
   has_attached_file :picture, :styles => {:small => "150x150", :large => "550x550"}
   process_in_background :picture
end

In my Rakefile I set: 
require 'resque/tasks'

I tryed to use delayed paperclip sach as a plugin, but just works in development environment in my machine local

 Thanks

**Comment by gotjosh** [comment]
I'm having exactly the same problem but in development any ideas?

**Comment by jstorimer** [comment]
@gotjosh Same as I said before, that setup is working for me. Can you try starting a fresh app and see if you can record the steps to reproduce it?

**Comment by RKushnir** [comment]
Why is this issue closed? It still fails the same way.

UPD. You're doing something wrong with your versions. I re-installed from GitHub and it works now. The source code from previous installation was quite different from the current, but was showing version 0.6.5 as if it was the same version.
