### ISSUE TITLE
undefined method most_appropriate_url with Paperclip 2.4.5

### ISSUE THREAD

**Issue by rnaud** [jstorimer/delayed_paperclip#54]
Hello !

Here is my bug : 

/Users/rnaud/.rvm/gems/ruby-1.9.2-p290/bundler/gems/rails-b7c7f08c87a8/activesupport/lib/active_support/core_ext/module/aliasing.rb:31:in `alias_method': undefined method`most_appropriate_url' for class `Paperclip::Attachment' (NameError)

using in my gem file : 
Using paperclip (2.4.5) from git://github.com/thoughtbot/paperclip.git (at master) 
Using delayed_paperclip (2.4.5.1) from git://github.com/jstorimer/delayed_paperclip.git (at master)

**Comment by basayel** [comment]
same here, Anyone reached a solution?

**Comment by aguilarsoto** [comment]
I got that same problem when using paperclip 2.5 but when reverting it back to 2.4.5 I got it working again.

**Comment by basayel** [comment]
Changing paperclip to 2.4.5 made it work! .. Thanks @aguilarsoto alot

**Comment by maxigs** [comment]
with commented out line:

```
#base.alias_method_chain :most_appropriate_url, :processed
```

the processing seems to work fine as well as the url output (as far as i tested as part of a project)
i tested against the current master of the paperclip repo (with the same error before).

i dont really know where to start looking for the root cause but this way paperclip and delayed-paperclip at least work togeter again in the latest version for who else needs it to

**Comment by aguilarsoto** [comment]
the short answer is that the most_appropriate_url was moved from the attachment to the url_generator and probably the call is different now, when i got a spare minute I can probably came up with a patch for delayed_paperclip

lib/paperclip/attachment.rb:    def most_appropriate_url

is moved to 

lib/paperclip/url_generator.rb:    def most_appropriate_url

regards,
Marco Aguilar

**Comment by atd** [comment]
Same problem here.

@aguilarsoto a patch will be warmly welcomed!

**Comment by aguilarsoto** [comment]
Hi gents, 

the fix has being submited as a pull request its a simple change if you want to see it here it is.

https://github.com/aguilarsoto/delayed_paperclip/commit/c4d361282d277753f8ea39848e12578fbed63289

Regards,
Marco

**Comment by aguilarsoto** [comment]
seems like I made a mistake here... fixing it now....

**Comment by jamesearl** [comment]
I'm still having this issue with 2.7

/home/james/dev/baus/paperclip/ruby/1.8/gems/activesupport-3.1.3/lib/active_support/core_ext/module/aliasing.rb:31:in `alias_method': undefined method`most_appropriate_url' for class `Paperclip::Attachment' (NameError)

paperclip (2.7.0)
      activerecord (>= 2.3.0)
      activesupport (>= 2.3.2)
      cocaine (>= 0.0.2)
      mime-types

**Comment by tdelam** [comment]
+1 I too have the same issue

**Comment by tommeier** [comment]
Fixed in : https://github.com/jstorimer/delayed_paperclip/pull/62

**Comment by amitsaxena** [comment]
+1
I have the same problem with paperclip version 2.6.0
